services:
  db:
    image: mysql:8.0
    container_name: badminton_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: ["3308:3306"]
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./api/MyAPI/MyAPI
    container_name: badminton_backend
    environment:
      ASPNETCORE_URLS: http://+:5211
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    ports: ["5211:5211"]

  frontend:
    build: ./frontend
    container_name: badminton_frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports: ["3000:3000"]
    command: npm run dev -- --hostname 0.0.0.0 --port 3000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports: ["8080:80"]
    depends_on:
      - db

volumes:
  db_data:
